auctions/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import (IndexView, CategoryView, ListingsByCatView,
    DetailedListingView, ListingsByOwnerView, BiddingView, AddListingView,
    AddToWatchlist, WatchlistView, CloseListingView, SearchView)


app_name = 'auctions'

urlpatterns = [
    # listings
    path('search/', SearchView.as_view(), name='search_listing'),
    path('', IndexView.as_view(), name='index'),
    path('categories/', CategoryView.as_view(), name='categories'),
    path('<slug:cat_slug>/',
        ListingsByCatView.as_view(), name='listings'),

    path('<slug:cat_slug>/<slug:listing_slug>/',
        DetailedListingView.as_view(), name='listing'),

    # user actions
    path('add_listing', login_required(AddListingView.as_view()),
        name='add_listing'),

    path('watchlist', login_required(WatchlistView.as_view()),
        name='get_watchlist'),

    path('<slug:cat_slug>/<slug:listing_slug>/add_to_watchlist',
        login_required(AddToWatchlist.as_view()), name="watch"),

    path('<slug:cat_slug>/<slug:listing_slug>/close_listing',
        login_required(CloseListingView.as_view()), name="close_listing"),

    path('my-listings', login_required(ListingsByOwnerView.as_view()),
        name='get_users_listings'),

    path('bidding', login_required(BiddingView.as_view()), name='bidding'),
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('analytics/', include('graphs.urls')),
    path('', include('auctions.urls')),
    path('account/', include('account.urls')),
    path('api/v1/', include('auctions_api.urls')),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

graphs/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import CategoryAnalyticsView


app_name = 'graphs'

urlpatterns = [
    path('', login_required(CategoryAnalyticsView.as_view()), name='cat_graph'),
]

auctions/models.py
from decimal import Decimal

from django.db import models
from django.urls import reverse
from django.core.validators import MinValueValidator

from account.models import User


class Category(models.Model):
    """A category model."""

    name = models.CharField(max_length=80)
    slug = models.SlugField(max_length=80, unique=True)

    class Meta:
        verbose_name_plural = 'Categories'
        ordering = ['name']

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self):
        return reverse('auctions:listings', args=[self.slug])

class Listing(models.Model):
    """A listing model."""

    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField()
    start_bid = models.DecimalField(max_digits=9, decimal_places=2,
        validators=[MinValueValidator(Decimal('0.01'))])
    image = models.URLField(blank=True)
    is_active = models.BooleanField(default=True)
    date_added = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self):
        return reverse('auctions:listing', kwargs={
            'cat_slug': self.category.slug, 'listing_slug': self.slug
        })

class Bid(models.Model):
    """A bid model."""

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE)
    bid = models.DecimalField(max_digits=19, decimal_places=2)
    date_added = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

class Comment(models.Model):
    """A comment model."""

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE)
    text = models.TextField(max_length=3000)
    date_added = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    # is_active = models.BooleanField(default=False)

class Watchlist(models.Model):
    """A watchlist model."""

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

auctions/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from .models import Listing, Bid, Comment


class ListingForm(forms.ModelForm):
    """A listing form.
    Contains fields: `category`, `name`, `image`, `start_bid`,
    and `description`.
    """

    class Meta:
        model = Listing
        fields = (
            'category', 'name',
            'image', 'start_bid',
            'description'
        )
        labels = {
            'name': 'Listing name', 'category': 'Category',
            'description': 'Description', 'start_bid': 'Start bid',
            'image': 'Image URL'
        }

class BidForm(forms.ModelForm):
    """A bid form.
    Contains fields: `bid`, `listing`.
    """

    class Meta:
        model = Bid
        fields = ('bid', 'listing')
        labels = {'bid': 'Your Bid'}
        widgets = {'listing': forms.HiddenInput()}

    def clean(self):
        """Validate a new bid."""

        new_bid = self.cleaned_data.get('bid')
        listing = self.cleaned_data.get('listing')
        start_bid = listing.start_bid
        bids = listing.bid_set.order_by('-date_added')
        current_bid = bids[0].bid if bids else start_bid

        if new_bid <= current_bid:
            self._errors['bid'] = self.error_class([
                'Bid must be higher than current.'])
            raise ValidationError(
                _('Invalid value: %(value)s'),
                code='invalid',
                params={'value': new_bid},
            )
        return self.cleaned_data

class CommentForm(forms.ModelForm):
    """A comment form.
    Contains field `text`.
    """

    class Meta:
        model = Comment
        fields = ('text',)
        labels = {'text': 'Comment'}

auctions/views.py
from copy import copy

from django.contrib.auth import get_user_model
from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.utils.text import slugify
from django.contrib.postgres.search import SearchVector
from django.views.generic import (ListView, DetailView, View,
    FormView, RedirectView)

from .models import Category, Listing, Watchlist
from .forms import ListingForm, BidForm, CommentForm
from .mixins import GetListingsQuerySetMixin


User = get_user_model()


class CategoryView(ListView):
    """Render a list of categories."""

    model = Category
    template_name = 'auctions/categories.html'
    context_object_name = 'categories'

    def get_queryset(self):
        """Return a queryset of categories."""

        return self.model.objects.all()


class SearchView(GetListingsQuerySetMixin, ListView):
    """Render page that depends on user's request."""

    paginate_by = 15
    template_name = 'auctions/listing_search.html'
    context_object_name = 'listing_search'
    model = Listing

    def get_queryset(self):
        """Call a `get_listingset` function to get a query of listings.
        Filter the query by a search request.
        """

        search_request = self.request.GET.get('q')
        query = self.get_listingset().annotate(search=SearchVector(
            'name', 'description', 'user__username'))
        if search_request:
            query = query.filter(search=search_request)

        return query


class IndexView(GetListingsQuerySetMixin, ListView):
    """Render the homepage, set by a number of listings per page and
    template name.
    """

    paginate_by = 15
    model = Listing
    template_name = 'auctions/index.html'
    context_object_name = 'active_listings'

    def get_queryset(self):
        """Call a `get_listingset` function to get a query of listings.
        Return the query filtered by `is_active=True`.
        """

        return self.get_listingset().filter(is_active=True)


class ListingsByCatView(GetListingsQuerySetMixin, ListView):
    """Render listings by chosen category."""

    paginate_by = 15
    model = Listing
    template_name = 'auctions/listings_by_cat.html'
    context_object_name = 'listings'

    def get_queryset(self):
        """Call a `get_listingset` function to get a query of listings.
        Return the query filtered by `is_active=True` and `cat_slug`.
        """

        return self.get_listingset().filter(is_active=True, category__slug=self.kwargs['cat_slug'])

    def get_context_data(self, **kwargs):
        """Return context by category."""

        context = super().get_context_data(**kwargs)
        context['category'] = get_object_or_404(Category, slug=self.kwargs['cat_slug'])
        return context


class ListingsByOwnerView(GetListingsQuerySetMixin, ListView):
    """Render listings created by a user."""

    paginate_by = 20
    model = Listing
    template_name = 'auctions/users_listings.html'
    context_object_name = 'users_listings'

    def get_queryset(self):
        """Call a `get_listingset` function to get a query of listings.
        Return the query filtered by `user` (owner).
        """

        query = self.get_listingset().filter(user=get_object_or_404(
            User, username=self.request.user))

        return query


class GetFilledForm(View):
    """Check which form has been filled. Depends on `DetailedListingView`"""

    model = Listing
    bid_form_class = BidForm
    comment_form_class = CommentForm

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        """Check `POST` request for type of submit. Depends on request
        build a filled form for bid or comment. Redirect to the listing page if
        form is valid. Otherwise append invalid data to context and rerender
        the page.
        """

        self.object = self.get_object()
        context = {}
        post_data = copy(self.request.POST)
        post_data['listing'] = self.object

        if 'bid_submit' in request.POST:
            form = self.bid_form_class(post_data)
        elif 'comment_submit' in request.POST:
            form = self.comment_form_class(post_data)

        if form.is_valid():
            form_data = form.save(commit=False)
            form_data.user = self.request.user
            form_data.listing = self.object
            form_data.save()
            return redirect(self.object.get_absolute_url())
        elif isinstance(form, BidForm) and not form.is_valid():
            context['bid_form'] = form
        elif isinstance(form, CommentForm) and not form.is_valid():
            context['comment_form'] = form
        return self.render_to_response(self.get_context_data(**context))


class DetailedListingView(GetFilledForm, DetailView):
    """Render a detailed listing page with a bid and a comment forms."""

    model = Listing
    template_name = 'auctions/listing.html'
    slug_url_kwarg = 'listing_slug'
    context_object_name = 'listing'


    def get_context_data(self, **kwargs):
        """Collect and return a context. Contains:
        Extra data: `cat_slug`,
        `comments`, `current_bid`, `current_bid_owner`, `bid_count`,
        `in_watchlist`.
        Forms: `comment_form`, `bid_form`.
        """

        context = super().get_context_data(**kwargs)
        context['cat_slug'] = self.kwargs['cat_slug']
        context['listing_slug'] = self.kwargs['listing_slug']
        context['start_bid'] = self.object.start_bid
        context['listing_owner'] = self.object.user
        context['comments'] = self.object.comment_set.order_by('-date_added')

        bids = self.object.bid_set.order_by('-bid')
        if bids:
            context['current_bid'] = bids[0].bid
            context['current_bid_owner'] = bids[0].user
            context['bid_count'] = len(bids)

        if self.request.user.is_authenticated:
            context['in_watchlist'] = User.objects.get(
                username=self.request.user).watchlist_set.filter(listing=self.object)

            context['comment_form'] = self.comment_form_class()

            is_author = self.request.user == context['listing_owner']
            is_last_bidder = False
            if bids:
                is_last_bidder = bids[0] == self.request.user

            if not is_author and not is_last_bidder and self.object.is_active and not context.get('bid_form'):
                bid_form = self.bid_form_class()
                context['bid_form'] = bid_form

        return context


class AddListingView(FormView):
    """Render a page with a create listing form."""

    form_class = ListingForm
    template_name = 'auctions/add_listing.html'

    def get_context_data(self, **kwargs):
        """Return form context."""

        context = super().get_context_data(**kwargs)
        context['listing_form'] = context['form']
        return context

    def form_valid(self, form):
        """Fill user and slug fields of the validated form and save it.
        Redirect to just created listing page.
        """

        listing = form.save(commit=False)
        listing.user = self.request.user
        listing_id = Listing.objects.filter(category=listing.category).count() + 1
        listing.slug = slugify(f'{listing.name}_{listing_id}')
        listing.save()
        return redirect(listing.get_absolute_url())


class CloseListingView(RedirectView):
    """Close a listing."""

    permanent = False
    query_string = True
    pattern_name = 'close_listing'

    def deactivate_listing(self, listing):
        """Set `is_active` parameter to `False` for the listing. Return
        the listing.
        """

        if listing.user == self.request.user:
            listing.is_active = False
            listing.save()
        return listing

    def get_redirect_url(self, *args, **kwargs):
        """Get a listing by a slug. Call `deactivate_liting` function.
        Redirect to a listing page.
        """

        listing = get_object_or_404(Listing, slug=kwargs['listing_slug'])
        listing = self.deactivate_listing(listing)

        return listing.get_absolute_url()


class BiddingView(ListView):
    """Render list of bids made by a user."""

    paginate_by = 20
    model = Listing
    template_name = 'auctions/bidding.html'
    context_object_name = 'bids'

    def get_queryset(self):
        user = get_object_or_404(User,  username=self.request.user)
        return user.bid_set.order_by('-date_added')


class WatchlistView(GetListingsQuerySetMixin, ListView):
    """Render user's watchlist watchlist."""

    paginate_by = 20
    model = Watchlist
    template_name = 'auctions/watchlist.html'
    context_object_name = 'watchlist'

    def get_queryset(self):
        """Call a `get_listingset` function to get a query of listings.
        Return query of listings watched by a user.
        """

        query = self.get_listingset().filter(
            watchlist__user=get_object_or_404(User, username=self.request.user
            ))

        return query


class AddToWatchlist(RedirectView):
    """Add a listing to a user's watchlist."""

    permanent = False
    query_string = True
    pattern_name = 'watch'
    model = Watchlist

    def watch_or_unwatch(self, listing):
        """Add a listing to the watchlist or delete from it."""

        if self.request.user != listing.user:
            watchlist, created = self.model.objects.get_or_create(
                user=self.request.user, listing=listing)
            if not created:
                watchlist.delete()

    def get_redirect_url(self, *args, **kwargs):
        """Get a listing by a slug. Call `watch_or_unwatch` function. Redirect
        to just watched/unwatched listing page.
        """

        listing = get_object_or_404(Listing, slug=kwargs['listing_slug'])
        self.watch_or_unwatch(listing)

templates/auctions/add_listing.html
{% extends 'layout.html' %}

{% block title %}Add listing{% endblock title %}

{% block body %}
    <div class="basic-title">
        <h1 class="page-title">Add listing</h1>
    </div>
    
    <div class="form-field">
        <form action="{% url 'auctions:add_listing' %}" method='POST'>
            {% csrf_token %}
            {% for field in listing_form %}
                <div class="field-form">
                    <div class="field-label">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    </div>
                    <div class="field">
                        {{ field }}
                    </div>
                    <div class="field-error">
                        {{ field.errors }}
                    </div>
                </div>
            {% endfor %}
            <div class="sbmt-btn">
                <button class="add-listing-btn" type="submit">Add Listing</button>
            </div>
        </form>
    </div>
{% endblock body %}

templates/auctions/bidding.html
{% extends 'layout.html' %}

{% block title %}Bidding{% endblock title %}

{% block body %}
    <div class="basic-title">
        <h1 class="page-title">My bids</h1>
    </div>
    
    {% if bids %}
        <div class="wlst">
            {% for bid in bids %}
                <a class="wlst-url" href="{{bid.listing.get_absolute_url}}">
                    <div class="wlst-img">
                        {% if bid.listing.image %}
                            <img class="wlst-img" src="{{ bid.listing.image }}" alt="{{ bid.listing.name }}">
                        {% else %}
                            <img class="wlst-img" src="https://media.istockphoto.com/vectors/default-image-icon-vector-missing-picture-page-for-website-design-or-vector-id1357365823?b=1&k=20&m=1357365823&s=170667a&w=0&h=y6ufWZhEt3vYWetga7F33Unbfta2oQXCZLUsEa67ydM=" alt="No image available">
                        {% endif %}
                    </div>
                    <div class="lst-name">
                        {{ bid.listing.name }}
                    </div>
                    <div class="lst-bid">
                        <small>Your bid:</small> US ${{ bid.bid }}
                    </div>
                </a>
            {% endfor %}
        </div>
    {% else %}
        There's nothing here yet.
    {% endif %}
{% endblock body %}

templates/auctions/index.html
{% extends "layout.html" %}

{% block title %}Active listings{% endblock title %}

{% block body %}
    <div class="basic-title">
        <h1 class="page-title">Active Listings</h1>
    </div>

    <div class="filtering-panel">
        <div class="radio">
            <label class="form-label" for="sort">Sort by:</label>
            <form id="sort" class="rad-form" action="{% url 'auctions:index' %}" method="GET">
                <input class="rad-point" type="radio" id="all" name="bid_filter" value="all" {% if not request.GET.bid_filter or request.GET.bid_filter == "all" %}checked{% endif %}>
                <label class="rad-label" for="all">Show all</label>
                <input class="rad-point" type="radio" id="no-bids" name="bid_filter" value='no_bids'{% if request.GET.bid_filter == "no_bids" %}checked{% endif %}>
                <label class="rad-label" for="no-bids">Without bids</label>
                <input class="rad-point" type="radio" id="bids" name="bid_filter" value="bids"{% if request.GET.bid_filter == "bids" %}checked{% endif %}>
                <label class="rad-label" for="bids">With bids</label>

                <select class="select-ordering" name="lst_sort" id="slct-sort">
                    <option value="date_desc" {% if request.GET.lst_sort == "date_desc" %}selected{% endif %}>Date Desc</option>
                    <option value="date_asc" {% if request.GET.lst_sort == "date_asc" %}selected{% endif %}>Date Asc</option>
                    <option value="name" {% if request.GET.lst_sort == "name" %}selected{% endif %}>Name</option>
                    <option value="bid_asc" {% if request.GET.lst_sort == "bid_asc" %}selected{% endif %}>Bid Asc</option>
                    <option value="bid_desc" {% if request.GET.lst_sort == "bid_desc" %}selected{% endif %}>Bid Desc</option>
                </select>

                <input class="sort-btn" type="submit" value="Sort">
            </form>
        </div>
    </div>

    {% if active_listings %}
        <div class="active_listings">
            {% for listing in active_listings %}
                <a class="listing_mini" href="{{ listing.get_absolute_url }}">
                    <div class="lst-img">
                        {% if listing.image %}
                            <img class="limg" src="{{ listing.image }}" alt="{{ listing.name }}">
                        {% else %}
                            <img class="limg" src="https://media.istockphoto.com/vectors/default-image-icon-vector-missing-picture-page-for-website-design-or-vector-id1357365823?b=1&k=20&m=1357365823&s=170667a&w=0&h=y6ufWZhEt3vYWetga7F33Unbfta2oQXCZLUsEa67ydM=" alt="No image available">
                        {% endif %}
                    </div>
                    <div class="lst-name">
                        {{ listing.name }}
                    </div>
                    <div class="lst-bid">
                        {% if listing.max_bid %}
                            <small>Current bid:</small> US ${{ listing.current_bid }}
                        {% else %}
                            <small>Starting bid:</small> US ${{ listing.start_bid }}
                        {% endif %}
                    </div>
                    <div class="lst-descr">
                        <h4 class="h4-descr">Description</h4>
                        <p class="descr">
                            {{ listing.description }}
                        </p>
                    </div>
                </a>
            {% endfor %}
        </div>
    {% else %}
        Sorry, there's nothing here yet.
    {% endif %}
{% endblock %}

templates/auctions/listing.html
{% extends 'layout.html' %}

{% block title %}{{ listing.name }}{% endblock title %}

{% block body %}
    <div class="lst-grid">
        <div class="lg-img">
            {% if listing.image %}
                <img class="lg-img-big" src="{{ listing.image }}" alt="{{ listing.name }}">
            {% else %}
                <img class="lg-img-big" src="https://media.istockphoto.com/vectors/default-image-icon-vector-missing-picture-page-for-website-design-or-vector-id1357365823?b=1&k=20&m=1357365823&s=170667a&w=0&h=y6ufWZhEt3vYWetga7F33Unbfta2oQXCZLUsEa67ydM=" alt="No image available">
            {% endif %}
        </div>

        <div class="lg-name">
            <h1 class="lst-title">{{ listing.name }}</h1>
        </div>
        
        <div class="lg-actions">
            <div class="cur-bid">
                {% if current_bid %}
                    <div>Current bid: <span id="price">US ${{ current_bid }}</span></div>
                    <div>{{ bid_count }}
                        {% if bid_count == 1 %}
                            bid
                        {% elif bid_count > 1 %}
                            bids
                        {% endif %}
                    </div>
                {% else %}
                    <div>Starting bid: <span id="price">US ${{ start_bid }}</span></div>
                {% endif %}
            </div>
    
            <div class="new-bid-info">
                {% if user.is_authenticated and user != listing_owner and user != current_bid_owner %}
                    {% if listing.is_active %}
                        <form id="id-bid-form" method="POST">
                            {% csrf_token %}
                            {{ bid_form.bid }}
                            <button id="make-bid" type="submit" name="bid_submit" value="bid">Bid</button>
                            {% if bid_form.bid.errors %}
                                <div class="errors">
                                    <ul class="field-errors-ul">
                                        {% for error in bid_form.bid.errors %}
                                            <li>{{ error }}</li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            {% endif %}
                        </form>
                    {% endif %}
                {% elif user == current_bid_owner and listing.is_active %}
                    <h3>Your bid leads</h3>
                {% elif user == listing_owner and listing.is_active %}
                    <a id="gla-btn" href="{% url 'auctions:close_listing' cat_slug listing_slug %}">Close listing</a>
                {% endif %}
                {% if not listing.is_active and user == current_bid_owner %}
                    <h3>Your bid won!</h3>
                {% elif not listing.is_active and max_bid and user != current_bid_owner %}
                    <h3>Winner: {{ current_bid_owner }}</h3>
                {% elif not listing.is_active and not max_bid %}
                    <h3>Closed without arriving bids.</h3>
                {% endif %}
            </div>

            {% if user.is_authenticated and user != listing_owner and listing.is_active %}
                <div class="watchlist">
                    <a id="gla-btn" href="{% url 'auctions:watch' cat_slug listing_slug %}">
                        {% if in_watchlist %}
                            Unwatch
                        {% else %}
                            Watch
                        {% endif %}
                    </a>
                </div>
            {% endif %}
        </div>

        <div class="lg-seller">
            <span>
                Seller: {{ listing_owner }}
            </span>
        </div>
        <div class="lg-descr">
            <h3>Description</h3>
            {{ listing.description|linebreaks }}
        </div>
    </div>

    {% if user.is_authenticated %}
        <div class="lg-add-comment">
            <details>
                <summary>Add a comment</summary>
                <form class="comment-form" method="POST">
                    {% csrf_token %}
                    {{ comment_form.text }}
                    <div class="sbmt-btn">
                        <button id="comment" type="submit" name="comment_submit" value="comment">Comment</button>
                    </div>
                </form>
            </details>
        </div>
    {% endif %}
    
        <div class="lg-comments">
            <h3 id="comments-header">
                Comments: {{ comments.count }}
            </h3>
            {% if comments %}
                {% for comment in comments %}
                    <div class="comment">
                        <div class="comment-title">
                            by <b>{{ comment.user }}</b> <i>added {{ comment.date_added }}</i>
                        </div>
                        <div class="comment-text">
                            {{ comment.text }}
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <div style="border-bottom: solid 1px rgba(0,0,0,.1);">
                    <i>No comments for this listing yet.</i>
                </div>
            {% endif %}
        </div>
{% endblock body %}

templates/auctions/listing_search.html
{% extends "layout.html" %}

{% block title %}Search results{% endblock title %}

{% block body %}
    <div class="basic-title">
        <h1 class="page-title">Search results</h1>
    </div>

    <div class="filtering-panel">
        <div class="radio">
            <label class="form-label" for="sort">Sort by:</label>
            <form id="sort" class="rad-form" action="{% url 'auctions:search_listing' %}" method="GET">
                <input class="rad-point" type="radio" id="all" name="bid_filter" value="all" {% if not request.GET.bid_filter or request.GET.bid_filter == "all" %}checked{% endif %}>
                <label class="rad-label" for="all">Show all</label>
                <input class="rad-point" type="radio" id="no-bids" name="bid_filter" value='no_bids'{% if request.GET.bid_filter == "no_bids" %}checked{% endif %}>
                <label class="rad-label" for="no-bids">Without bids</label>
                <input class="rad-point" type="radio" id="bids" name="bid_filter" value="bids"{% if request.GET.bid_filter == "bids" %}checked{% endif %}>
                <label class="rad-label" for="bids">With bids</label>

                <select class="select-ordering" name="lst_sort" id="slct-sort">
                    <option value="date_desc" {% if request.GET.lst_sort == "date_desc" %}selected{% endif %}>Date Desc</option>
                    <option value="date_asc" {% if request.GET.lst_sort == "date_asc" %}selected{% endif %}>Date Asc</option>
                    <option value="name" {% if request.GET.lst_sort == "name" %}selected{% endif %}>Name</option>
                    <option value="bid_asc" {% if request.GET.lst_sort == "bid_asc" %}selected{% endif %}>Bid Asc</option>
                    <option value="bid_desc" {% if request.GET.lst_sort == "bid_desc" %}selected{% endif %}>Bid Desc</option>
                </select>

                <input class="sort-btn" type="submit" value="Sort">
            </form>
        </div>
    </div>

    {% if listing_search %}
        <div class="active_listings">
            {% for listing in listing_search %}
                <a class="listing_mini" href="{{ listing.get_absolute_url }}">
                    <div class="lst-img">
                        {% if listing.image %}
                            <img class="limg" src="{{ listing.image }}" alt="{{ listing.name }}">
                        {% else %}
                            <img class="limg" src="https://media.istockphoto.com/vectors/default-image-icon-vector-missing-picture-page-for-website-design-or-vector-id1357365823?b=1&k=20&m=1357365823&s=170667a&w=0&h=y6ufWZhEt3vYWetga7F33Unbfta2oQXCZLUsEa67ydM=" alt="No image available">
                        {% endif %}
                    </div>
                    <div class="lst-name">
                        {{ listing.name }}
                    </div>
                    <div class="lst-bid">
                        {% if listing.max_bid %}
                            <small>Current bid:</small> US ${{ listing.max_bid }}
                        {% else %}
                            <small>Starting bid:</small> US ${{ listing.start_bid }}
                        {% endif %}
                    </div>
                    <div class="lst-descr">
                        <h4 class="h4-descr">Description</h4>
                        <p class="descr">
                            {{ listing.description }}
                        </p>
                    </div>
                </a>
            {% endfor %}
        </div>
    {% else %}
        Sorry, we haven't found anything relevant to <b>{{ request.GET.q }}</b>.
    {% endif %}
{% endblock %}