account/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.decorators import login_required

# from .views import register
from .views import (RegisterView, LogInView, LogOutView, UserView,
    ChangeInfoView, ChangePassView, ChangePassDoneView)


app_name = 'account'

urlpatterns = [
    path('login', LogInView.as_view(), name='login'),
    path('logout', LogOutView.as_view(), name='logout'),
    path('register', RegisterView.as_view(success_url=reverse_lazy(
        'account:login')), name='register'),
    path('details', login_required(UserView.as_view()), name='acc_details'),
    path('change-password', login_required(
        ChangePassView.as_view(success_url=reverse_lazy(
            'account:password_change_done'))),
        name='change_pass'),

    path('change-password/success', login_required(
        ChangePassDoneView.as_view()),
        name='password_change_done'),

    path('change-info', login_required(ChangeInfoView.as_view()),
        name='change_info'),
]

auctions/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import (IndexView, CategoryView, ListingsByCatView,
    DetailedListingView, ListingsByOwnerView, BiddingView, AddListingView,
    AddToWatchlist, WatchlistView, CloseListingView, SearchView)


app_name = 'auctions'

urlpatterns = [
    # listings
    path('search/', SearchView.as_view(), name='search_listing'),
    path('', IndexView.as_view(), name='index'),
    path('categories/', CategoryView.as_view(), name='categories'),
    path('<slug:cat_slug>/',
        ListingsByCatView.as_view(), name='listings'),

    path('<slug:cat_slug>/<slug:listing_slug>/',
        DetailedListingView.as_view(), name='listing'),

    # user actions
    path('add_listing', login_required(AddListingView.as_view()),
        name='add_listing'),

    path('watchlist', login_required(WatchlistView.as_view()),
        name='get_watchlist'),

    path('<slug:cat_slug>/<slug:listing_slug>/add_to_watchlist',
        login_required(AddToWatchlist.as_view()), name="watch"),

    path('<slug:cat_slug>/<slug:listing_slug>/close_listing',
        login_required(CloseListingView.as_view()), name="close_listing"),

    path('my-listings', login_required(ListingsByOwnerView.as_view()),
        name='get_users_listings'),

    path('bidding', login_required(BiddingView.as_view()), name='bidding'),
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('analytics/', include('graphs.urls')),
    path('', include('auctions.urls')),
    path('account/', include('account.urls')),
    path('api/v1/', include('auctions_api.urls')),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

graphs/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import CategoryAnalyticsView


app_name = 'graphs'

urlpatterns = [
    path('', login_required(CategoryAnalyticsView.as_view()), name='cat_graph'),
]

templates/layout.html
{% load static %}
{% load mathfilters %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}{% endblock title %}</title>
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
        <link rel="icon" href="{% static 'auctions/box-seam-white.svg' %}" sizes="any">
    </head>
    <body>
        <div class="header">
            <div class="logo">
                <a class="nav-link" href="{% url 'auctions:index' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="17" height="17" fill="currentColor" class="bi bi-box-seam" viewBox="0 0 16 16">
                        <path d="M8.186 1.113a.5.5 0 0 0-.372 0L1.846 3.5l2.404.961L10.404 2l-2.218-.887zm3.564 1.426L5.596 5 8 5.961 14.154 3.5l-2.404-.961zm3.25 1.7-6.5 2.6v7.922l6.5-2.6V4.24zM7.5 14.762V6.838L1 4.239v7.923l6.5 2.6zM7.443.184a1.5 1.5 0 0 1 1.114 0l7.129 2.852A.5.5 0 0 1 16 3.5v8.662a1 1 0 0 1-.629.928l-7.185 2.874a.5.5 0 0 1-.372 0L.63 13.09a1 1 0 0 1-.63-.928V3.5a.5.5 0 0 1 .314-.464L7.443.184z"/>
                    </svg>
                    AUCTIONS
                </a>
            </div>
            <input id="nav-toggle" type="checkbox" />
            <label class="nav-button-container" for="nav-toggle">
                <div class="nav-button"></div>
            </label>
            <div class="right-nav">
                <ul class="nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auctions:categories' %}">Categories</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'auctions:get_watchlist' %}">Watchlist</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'auctions:bidding' %}">Bidding</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'auctions:get_users_listings' %}">My listings</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'auctions:add_listing' %}">Add listing</a>
                        </li>
                    {% endif %}
                    <li class="nav-srch nav-item">
                        <form class="srch-form" action="{% url 'auctions:search_listing' %}" method='GET'>
                            <input class="srch-fld" type="text" name="q" value="{{ request.GET.q }}" placeholder="Enter your request here">
                            <input class="srch-btn" type="submit" value="Search">
                        </form>
                    </li>
                </ul>
                <ul class="signed-in-info">
                    {% if user.is_authenticated %}
                        <li class="signed-in-item">
                            <a class="nav-link" href="{% url 'account:acc_details' %}">
                                <strong>{{ user.username }}</strong>
                            </a>
                        </li>
                        <li class="signed-in-item">
                            <a class="nav-link" href="{% url 'account:logout' %}">
                                Log Out
                            </a>
                        </li>
                    {% else %}
                        <li class="signed-in-item">
                            <a class="nav-link" href="{% url 'account:register' %}">Register</a>
                        </li>
                        <li class="signed-in-item">
                            <a class="nav-link" href="{% url 'account:login' %}">
                                Log In
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>

        <div class="body">
            {% block body %}{% endblock body %}
        </div>
        {% if page_obj.has_other_pages %}
                <div class="pagination">
                    <ul class="content-pages">
                        {% if page_obj.number|add:-2 > 1 %}
                            <li class="page-num">
                                <a href="?page=1" class="basic-link">1</a>
                            </li>
                            {% if page_obj.number != 4 %}
                                <li class="three-dots">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="rgba(27, 73, 101, 0.6)" class="bi bi-three-dots" viewBox="0 0 16 3">
                                        <path d="M3 9.5a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3z"/>
                                    </svg>
                                </li>
                            {% endif %}
                        {% endif %}
                        {% for page in page_obj.paginator.page_range %}
                            {% if page_obj.number == page %}
                                <li class="curr-page-num">
                                    {{ page }}
                                </li>                                
                            {% elif page >= page_obj.number|add:-2 and page <= page_obj.number|add:2 %}
                                <li class="page-num">
                                    <a href="?page={{ page }}" class="basic-link">
                                        {{ page }}
                                    </a>
                                </li>
                            {% endif %}
                        {% endfor %}
                        {% if page_obj.number|add:2 < page_obj.paginator.num_pages %}
                            {% if page_obj.paginator.num_pages|sub:page_obj.number > 3 %}
                                <li class="three-dots">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="rgba(27, 73, 101, 0.6)" class="bi bi-three-dots" viewBox="0 0 16 3">
                                        <path d="M3 9.5a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3z"/>
                                    </svg>
                                </li>
                            {% endif %}
                            <li class="page-num">
                                <a href="?page={{ page_obj.paginator.num_pages }}" class="basic-link">{{ page_obj.paginator.num_pages }}</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            {% endif %}
        <div class="footer">
            <div>
                <a class="basic-link" id="footer_urls" href="{% url 'schema-swagger-ui' %}">API</a>
            </div>
            {% if user.is_authenticated %}
            <div>
                <a class="basic-link" id="footer_urls" href="{% url 'graphs:cat_graph' %}">Analytics</a>
            </div>
            {% endif %}
            <div>
                Copyright © 2021-2022 AUCTIONS Inc. All Rights Reserved. Joking :)
            </div>
        </div>
    </body>
</html>